name: PR Checks

on:
  pull_request:
    branches: [master]

jobs:
  check:
    name: Lint, Typecheck & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint Check
        run: npm run lint-check

      - name: TypeScript Check
        run: npm run tsc

      # Add .env.test, because of "test" script (dotenv -e .env.test)
      # environment:
      #   name: Test
      # Add vars to this file like this:
      # run: |
      # touch .env.test
      # echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env.test
      - name: Create dummy env file for tests
        run: |
          touch .env.test
          echo "NEXT_PUBLIC_API_URL=stub.com" >> .env.test
          echo "NEXT_PUBLIC_RECAPTCHA_SITE_KEY=stub" >> .env.test
          echo "NEXT_PUBLIC_CLOUDFLARE_CAPTCHA_SITE_KEY=stub" >> .env.test
          echo "NEXT_PUBLIC_SUPABASE_URL=stub.com" >> .env.test
          echo "NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=stub" >> .env.test
          echo "NEXT_PUBLIC_DEV_LOGGER=false" >> .env.test
          echo "NEXT_PUBLIC_SITE_URL=http://localhost:3000" >> .env.test

      - name: Run Unit Tests
        run: npm run test:run
